name = "evil transgender vaults"
author = "iwolfking, alyx"
version = "0.31.2-0.0.1dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8289a8c94ea93f43877aa12bac322f1a2b101bf59021e41a37c67c2d683c3292"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
