name = "Wold's Vaults"
author = "iwolfking"
version = "0.21.3-1.8.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8471973ef9d5d59d8f06c2fcb3fcf31dfadeca0759dfaf4817e79e8f1169771d"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
unsup = "1.0.2"
