name = "Wold's Vaults"
author = "iwolfking"
version = "0.21.1-1.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "006fb707279a7bd411b2ff5894474df50ee3ed121b7a2f5ba658202e925aa9c0"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
unsup = "1.0.2"
