name = "Wold's Vaults"
author = "iwolfking"
version = "0.22.0-1.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "951f5effeb4020ab422e4147b0887cd50c73f9e7c789f64e7ff4f7a6df1d9773"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
unsup = "1.0.2"
