name = "Wold's Vaults"
author = "iwolfking"
version = "0.22.0-1.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc06eabb23cdab0b651d57a413bc9ecc4c652528c124716eba4c98b70d376922"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
unsup = "1.0.2"
