name = "Wold's Vaults"
author = "iwolfking"
version = "0.21.6-1.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b75d20845e31189aafc10e40ec2de0d79c7f5a7870e80dc282ac00124d293c30"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
unsup = "1.0.2"
