name = "Wold's Vaults"
author = "iwolfking"
version = "0.21.3-1.8.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86196e66ac299785574b027ea252d67759bf430694cea55f6da91ab61cb42983"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
unsup = "1.0.2"
