name = "Wold's Vaults"
author = "iwolfking"
version = "0.22.0-1.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7cef7bdd44c581b56ed0ad0cbf90c172efc88f9166f59725afcae00305d8e142"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
unsup = "1.0.2"
