name = "Wold's Vaults"
author = "iwolfking"
version = "0.21.3-1.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f100b3b33ffa662421e9305f936d8f4408d8fcde0fc9e7f17dd262998f60f76e"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
unsup = "1.0.2"
