name = "Wold's Vaults"
author = "iwolfking"
version = "0.21.3-1.8.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4bb0b399ba270457c3a8397605183ca4241bc69108993c57a18a95bc96d6af6"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
unsup = "1.0.2"
