name = "Wold's Vaults"
author = "iwolfking"
version = "0.21.6-1.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6662f2bc107a3fd9b5d155e45bccb566581374b4a4ed39f2b74459585c23c184"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
unsup = "1.0.2"
