name = "Wold's Vaults"
author = "iwolfking"
version = "0.22.0-1.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6fafafee700e937adbf02803716eca03808b47d0cdb18fb21b4a4d8220529924"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
unsup = "1.0.2"
