name = "evil transgender vaults"
author = "iwolfking, alyx"
version = "0.31.2-0.0.1dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14623f8e6559a6ba75d72c316638da5055367ac43b113afa9bd62e0583445216"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
