name = "Wold's Vaults"
author = "iwolfking"
version = "0.22.0-1.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a112e8dd5f0bd0447c4073a9781df4f528c4de0bc5cbfd0760511d886bbc3cd"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
unsup = "1.0.2"
