name = "Wold's Vaults"
author = "iwolfking"
version = "0.22.0-1.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c323c0576d2e4331a1903af686eaa409e5fe9fd342750df1f588be8797a4fa5f"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
unsup = "1.0.2"
