name = "Wold's Vaults"
author = "iwolfking"
version = "0.22.0-1.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "917b66c339e0b528c46e05903e4a59f1801d1a382d2caf3c73c1253b6096547c"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
unsup = "1.0.2"
