name = "Wold's Vaults"
author = "iwolfking"
version = "0.21.3-1.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f4cd94780718921502bc44c07cc1135c5476c663b170aadd490efa04faa376b"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
unsup = "1.0.2"
