name = "Wold's Vaults"
author = "iwolfking"
version = "0.22.0-1.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5d58bbf3bbba570548748fe1f7d7c597125ec460c9163e4737fca26080494d2"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
unsup = "1.0.2"
