name = "Wold's Vaults"
author = "iwolfking"
version = "0.21.3-1.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7f841c978876bf01305ed987a504309ac73e8e658851988b9feacdd0b41b851"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
unsup = "1.0.2"
