name = "evil transgender vaults"
author = "iwolfking, alyx"
version = "0.31.2-0.0.1dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ecd7c8f3b7c1ddf4f4cf9617993811425cae386399547caeb96aa254e2793033"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
unsup = "1.2.7"
