name = "Wold's Vaults"
author = "iwolfking"
version = "0.21.3-1.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb6ce2a851edbf56ae5124e4f2473e348f309e209c2baef231fd91fea0bfcc56"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
unsup = "1.0.2"
