name = "Wold's Vaults"
author = "iwolfking"
version = "0.21.1-1.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c24e66bba3c3bf6537ac20f04bb247dcd3165f442ca4b7f801c3bffc3b9fb968"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
unsup = "1.0.2"
