
["Configs for Kendrome VH Tweaks"]
	#Shows relative values for jewel affixes in tooltips
	"Enable jewel relative tooltips" = true
	#Require key to show (None for always show)
	#Allowed Values: None, Shift, Alt, Ctrl, Tab
	"Jewel relative tooltips key" = "Shift"
	#Show gear comparison tooltips
	"Enable gear comparison tooltips" = true
	#Require key to show (None for always show)
	#Allowed Values: None, Shift, Alt, Ctrl, Tab
	"Gear Comparison tooltips key" = "Shift"
	#Should tooltips be compact (less spaces, etc)
	"Enable compact mode" = true
	#Show a rating instead of the relative value in jewel tooltips
	"Enable jewel rating tooltips" = false
	#Shows free cuts available for jewels in tooltips
	"Enable jewel free cuts tooltips" = false

