#List of player names used for skins
names = ["iwolfking", "KaiTheTinyKiwi", "LisicaQ", "caigan", "Cosmonite", "Afridqvist", "jackal9006", "Stayed91", "Inflectus", "BigSinisterToad", "jazzmickle", "Palsonny", "sengia2002", "MonstaKilla2001", "Nob0dy101", "dearliest", "Panda413", "FreedomDefender", "bradmin", "PacketNarc", "Rais_Codex", "MasterTomer2003", "IvanPurr", "hackerslayer223", "SanoVictus", "JosephFranci", "StarWalker", "Araevin", "JoTachi", "FreeGore", "Drunksparrow", "REMZProd", "T_a_i_n", "Ritter_Rost", "Clone_HD", "HyemHyemu", "Winged_Fury", "Gloamy_", "Irenaiad", "neopeasant", "Red_IT", "Wayward__Wizard", "PigExile", "Wyxaldir", "LoveTerraria", "Neighthanael", "MRDeepEnd", "RichyEdits", "Karthaxus", "Kharonuk", "Spoony_Panda", "Devengel"]
#Chance for fighter to have skin
#Range: 0 ~ 100
skinChance = 10
#Disable stars in name that show fighter tier
disableStars = false
#Url of file containing names separated by newline (\n)
nameUrl = ""
#Where should skinfighters get skin names from
#Allowed Values: CONFIG, URL, CONFIG_AND_URL
nameSource = "CONFIG"

